### ISSUE TITLE
DownloadDiscoData ’XXXX md5 check failed‘

### ISSUE THREAD

**Issue by Dacy34** [JinmiaoChenLab/DISCOtoolkit#1]
Thank you very much for making the DISCOtoolkit R package. 
Recently, I have always encountered the error of' XXX md5 check failed', and downloading files has always failed. The two project currently encountered are GSE189903and GSE162025. I don't know whether these two data sets are not open for download or whether there is a network problem. However, the meta of data can be obtained from FilterDiscoMetadata. Besides, I can't download these two data on the DISCO web page.
![1683959747539](https://github.com/JinmiaoChenLab/DISCOtoolkit/assets/124675082/cada28e9-cbf2-4342-9f31-1f344ea0a325)

**Comment by lmw123** [comment]
Hi,

Thanks for your interest in DISCO Toolkit.

Regarding your question, could you update the DISCO toolkit to latest version and try again? We have recently added new data download functions, which were implemented yesterday.

Please feel free to contact us if you have any problems.

Best,
Mengwei

**Comment by Dacy34** [comment]
Hi, Mengwei
Thank you very much! The problem is really solved once upgraded! Thank you for making such an easy-to-use database and R package!
Best,
Mengtian
