### ISSUE TITLE
the download rds maybe wrong

### ISSUE THREAD

**Issue by zhoushican** [JinmiaoChenLab/DISCOtoolkit#2]
I  used the code to download the mast cell and merged them. But I encountered this error.
```library(DISCOtoolkit)
 library(Seurat)
 library(dplyr)
 metadata = FilterDiscoMetadata(
  sample = NULL,
  project = NULL,
  tissue = NULL,
  disease = NULL,
  platform = c("10x3'", "10x5'"),
  sample.type = NULL,
  cell.type ='Mast cell' , 
  cell.type.confidence = "high", 
  include.cell.type.children = T, 
  min.cell.per.sample = 50
)
download.log = DownloadDiscoData(metadata, output.dir = "disco_data")
dir='disco_data//' 
samples=list.files( dir ,pattern = 'rds')
samples 
sceList = lapply(samples,function(pro){ 
  print(pro)
  sce <- readRDS(file.path( dir ,pro))
  return(sce)
})
Error in readRDS(file.path(dir, pro)) : error reading from connection`

pro=samples[15] 
pro
[1] "ERX3382911_6.rds"
 sce <- readRDS(file.path( dir ,pro))
Error in readRDS(file.path(dir, pro)) : error reading from connection
```

Can you tell me what the problem is? 
I think maybe there is something wrong with this file ERX3382911_6.rds.
How can I download the function ERX3382911_6.rds separately?

**Comment by lmw123** [comment]
Hi,

Thanks for your interest in the DISCO toolkit.

To download the ERX3382911_6.rds file, please specify the sample using the following code:

metadata = FilterDiscoMetadata(
  sample = "ERX3382911",
  project = NULL,
  tissue = NULL,
  disease = NULL,
  platform = c("10x3'", "10x5'"),
  sample.type = NULL,
  cell.type ='Mast cell' , 
  cell.type.confidence = "high", 
  include.cell.type.children = T, 
  min.cell.per.sample = 50
)

Best,
Mengwei
