### ISSUE TITLE
cannot download the bone marrow atlas

### ISSUE THREAD

**Issue by cathalgking** [JinmiaoChenLab/DISCOtoolkit#4]
I cannot download the ```bone_marrow``` dataset on the DISCO database. I have tried downloading the bone_marrow RDS 2 ways and both returned incorrect hash keys (MD5) compared to what is listed on the DISCO web postal. First I tried with the download button on the web portal through chrome browser and then secondly with the wget command on terminal. In R, both attempts did not work when using the readRDS function.

https://www.immunesinglecell.org/atlas/bone_marrow

Can you let me know if this is the same on your end? Is there another way to access this file?

**Comment by lmw123** [comment]
Hi Cathal,

Thank you for pointing this out. I have tested it on my end, and the MD5 check is correct. I think the issue might be related to network connectivity. Our server is based in Singapore. I’ve uploaded the data you need to Google Drive, and you can download it from https://drive.google.com/file/d/1RjKNOg3e5EivlY27WjT3ym7dN4Uodfml/view?usp=drive_link. Please let me know if you have any other issues.

Best,
Mengwei
